---
- name: Create folder
  ansible.builtin.file:
    path: '{{ setup_vault_folder_path }}'
    state: directory
    mode: '0755'
    owner: '{{ setup_vault_folder_owner }}'
    group: '{{ setup_vault_folder_group }}'
  when: setup_vault_create_folder

- name: Create configfolder
  ansible.builtin.file:
    path: '{{ setup_vault_data_path }}/config'
    state: directory
    mode: '0755'
    owner: '{{ setup_vault_folder_owner }}'
    group: '{{ setup_vault_folder_group }}'

- name: Template vault.hcl
  ansible.builtin.template:
    src: 'vault.hcl.j2'
    dest: '{{ setup_vault_data_path }}/config/vault.hcl'
    owner: '{{ setup_vault_folder_owner }}'
    group: '{{ setup_vault_folder_group }}'
    mode: '0644'

- name: Template composefile
  ansible.builtin.template:
    src: 'compose.yaml.j2'
    dest: '{{ setup_vault_folder_path }}/compose.yaml'
    owner: '{{ setup_vault_folder_owner }}'
    group: '{{ setup_vault_folder_group }}'
    mode: '0644'

- name: Template vault env-file
  ansible.builtin.template:
    src: 'vaultenv.j2'
    dest: '{{ setup_vault_folder_path }}/.vaultenv'
    owner: '{{ setup_vault_folder_owner }}'
    group: '{{ setup_vault_folder_group }}'
    mode: '0644'
  when: setup_vault_transit

- name: Create network
  community.docker.docker_network:
    name: "{{ setup_vault_network }}"
  when: setup_vault_create_network

- name: Start compose-file
  community.docker.docker_compose_v2:
    project_src: '{{ setup_vault_folder_path }}'
    state: present
...
