---
argument_specs:
  main:
    short_description: 'docker compose up'
    description:
      - 'Take up a docker project with compose'
    options:
      compose_up_path:
        type: 'str'
        required: true
        description:
          - 'Path to the compose project to take down'

      compose_up_pull_policy:
        type: 'str'
        required: false
        default: 'missing'
        description:
          - 'Path to the compose project to take down'
...
