---
argument_specs:
  main:
    short_description: Setup Vault with compose
    description:
      - Setup Vault with compose
    options:
      setup_vault_folder_path:
        type: str
        required: true
        description:
          - Path of the compose-project

      setup_vault_folder_owner:
        type: str
        required: false
        default: root
        description:
          - Owner of the Folder and Files

      setup_vault_folder_group:
        type: str
        required: false
        default: root
        description:
          - Group of the Folder and Files

      setup_vault_create_folder:
        type: bool
        required: false
        default: false
        description:
          - Set, if the Folder should be created

      setup_vault_name:
        type: str
        required: true
        description:
          - Name for the project
          - Used for the composefile and traefik-router

      setup_vault_image:
        type: str
        required: false
        default: hashicorp/vault
        description:
          - Image to use for vault

      setup_vault_version:
        type: str
        required: false
        default: latest
        description:
          - Imagetag to use for vault

      setup_vault_network:
        type: str
        required: false
        description:
          - Set, if an external network should be used for vault

      setup_vault_create_network:
        type: bool
        required: false
        default: false
        description:
          - Set, if the network for vault should be created

      setup_vault_expose:
        type: bool
        required: false
        default: true
        description:
          - Set to false, if traefik is used or the vault should not expose a port

      setup_vault_external_port:
        type: str
        required: false
        default: 8201
        description:
          - Port, on which vault should be exposed

      setup_vault_data_path:
        type: str
        required: false
        default: ./data
        description:
          - Path, where the vault data should be stored
          - If recursive, the path starts in the compose-folder

      setup_vault_env_path:
        type: str
        required: false
        description:
          - Path, where the vault env-file should be stored
          - If recursive, the path starts in the compose-folder
          - If not defined, no env-file will be used

      setup_vault_token:
        type: str
        required: false
        description:
          - Token,
          - Will only be used in the vault_env file

      setup_vault_traefik:
        type: bool
        required: false
        default: false
        description:
          - Should traefik be enabled for the compose project

      setup_vault_traefik_default_labels:
        type: bool
        required: false
        default: true
        description:
          - Set to false, if the default-labels for traefik should not be used
          - Only required, when traefik is used

      setup_vault_traefik_fqdn:
        type: str
        required: false
        description:
          - FQDN, on which the vault should be exposed
          - Only required when traefik is used

      setup_vault_traefik_custom_labels:
        type: str
        required: false
        default: ''
        description:
          - Custom traefik-labels to set
          - Should be set as multiline-string
          - Only required when traefik is used
...
